name: Update Date Images
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
    
    - name: Generate date images
      run: |
        DATE=$(date +'%B %d, %Y')
        
        # Small text - no whitespace
        convert -background white -fill black \
                -pointsize 16 \
                label:"$DATE" \
                -trim +repage \
                date-small.png
                
        # Medium text - no whitespace
        convert -background white -fill black \
                -pointsize 24 \
                label:"$DATE" \
                -trim +repage \
                date.png
                
        # Large text - no whitespace
        convert -background white -fill black \
                -pointsize 32 \
                label:"$DATE" \
                -trim +repage \
                date-large.png
    
    - name: Commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add *.png
        git commit -m "Update date images" || exit 0
        git push
