name: Update Date Images
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
    
    - name: Generate date images
      run: |
        DATE=$(date +'%B %d, %Y')
        
        convert -size 300x75 xc:white \
                -pointsize 24 \
                -gravity center \
                -fill black \
                -annotate +0+0 "$DATE" \
                date.png
                
        convert -size 200x50 xc:white \
                -pointsize 16 \
                -gravity center \
                -fill black \
                -annotate +0+0 "$DATE" \
                date-small.png
                
        convert -size 400x100 xc:white \
                -pointsize 32 \
                -gravity center \
                -fill black \
                -annotate +0+0 "$DATE" \
                date-large.png
    
    - name: Commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add *.png
        git commit -m "Update date images" || exit 0
        git push
