name: Update Date Images
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install ImageMagick and setup fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick fonts-liberation
        
        # Create fonts directory
        mkdir -p ~/.fonts
        
        # Copy fonts - handle different structures
        # Open Sans
        find fonts/open-sans -name "*.ttf" -o -name "*.otf" | xargs -I {} cp {} ~/.fonts/ 2>/dev/null || true
        
        # Inter
        find fonts/inter -name "*.ttf" -o -name "*.otf" | xargs -I {} cp {} ~/.fonts/ 2>/dev/null || true
        
        # Times (if you have actual Times fonts)
        find fonts/times -name "*.ttf" -o -name "*.otf" | xargs -I {} cp {} ~/.fonts/ 2>/dev/null || true
        
        # Refresh font cache
        fc-cache -fv
        
        # Debug: Show what fonts we actually have
        echo "=== Font files copied ==="
        ls -la ~/.fonts/
        echo "=== Available fonts in system ==="
        fc-list : family | sort | uniq
    
    - name: Generate all date image variants
      run: |
        DATE=$(date +'%B %d, %Y')
        
        # Create images directory if it doesn't exist
        mkdir -p images
        
        # Clean up old images
        rm -f images/*.png
        
        # Define our options
        SIZES=(14 16 18 20 24 28 32)
        COLORS=("black:000000" "white:FFFFFF" "gray:666666" "darkgray:333333" "red:CC0000" "blue:0066CC")
        
        # Generate for Open Sans
        for size in "${SIZES[@]}"; do
          for color_pair in "${COLORS[@]}"; do
            color_name="${color_pair%%:*}"
            color_hex="#${color_pair##*:}"
            
            # Regular - try multiple possible font names
            convert -background transparent -fill "$color_hex" \
                    -font "Open-Sans-Regular" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-opensans_size-${size}_weight-regular_color-${color_name}.png" 2>/dev/null || \
            convert -background transparent -fill "$color_hex" \
                    -font "OpenSans-Regular" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-opensans_size-${size}_weight-regular_color-${color_name}.png" 2>/dev/null || \
            convert -background transparent -fill "$color_hex" \
                    -font "Open-Sans" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-opensans_size-${size}_weight-regular_color-${color_name}.png"
            
            # Bold
            convert -background transparent -fill "$color_hex" \
                    -font "Open-Sans-Bold" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-opensans_size-${size}_weight-bold_color-${color_name}.png" 2>/dev/null || \
            convert -background transparent -fill "$color_hex" \
                    -font "OpenSans-Bold" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-opensans_size-${size}_weight-bold_color-${color_name}.png" 2>/dev/null || \
            convert -background transparent -fill "$color_hex" \
                    -font "Open-Sans-SemiBold" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-opensans_size-${size}_weight-bold_color-${color_name}.png"
          done
        done
        
        # Generate for Inter
        for size in "${SIZES[@]}"; do
          for color_pair in "${COLORS[@]}"; do
            color_name="${color_pair%%:*}"
            color_hex="#${color_pair##*:}"
            
            # Regular
            convert -background transparent -fill "$color_hex" \
                    -font "Inter-Regular" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-inter_size-${size}_weight-regular_color-${color_name}.png" 2>/dev/null || \
            convert -background transparent -fill "$color_hex" \
                    -font "Inter" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-inter_size-${size}_weight-regular_color-${color_name}.png"
            
            # Bold
            convert -background transparent -fill "$color_hex" \
                    -font "Inter-Bold" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-inter_size-${size}_weight-bold_color-${color_name}.png" 2>/dev/null || \
            convert -background transparent -fill "$color_hex" \
                    -font "Inter-SemiBold" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-inter_size-${size}_weight-bold_color-${color_name}.png"
          done
        done
        
        # Generate for Times (using Liberation Serif)
        for size in "${SIZES[@]}"; do
          for color_pair in "${COLORS[@]}"; do
            color_name="${color_pair%%:*}"
            color_hex="#${color_pair##*:}"
            
            # Regular
            convert -background transparent -fill "$color_hex" \
                    -font "Liberation-Serif" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-times_size-${size}_weight-regular_color-${color_name}.png"
            
            # Bold
            convert -background transparent -fill "$color_hex" \
                    -font "Liberation-Serif-Bold" \
                    -pointsize "$size" \
                    label:"$DATE" \
                    -trim +repage \
                    "images/font-times_size-${size}_weight-bold_color-${color_name}.png"
          done
        done
        
        echo "Generated $(ls -1 images/*.png | wc -l) date images"
    
    - name: Commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add images/*.png
        git commit -m "Update date images - $(date +'%Y-%m-%d')" || exit 0
        git push
